version: '3.8'

services:
  coreai-mcu-prompts:
    build:
      target: development
    image: coreai-mcu-prompts-development
    container_name: coreai-mcu-prompts-development
    depends_on:
      - coreai-mcu-prompts-azurite
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json
    environment:
      AZURE_STORAGE_USE_CONNECTION_STRING: ${AZURE_STORAGE_USE_CONNECTION_STRING:-true}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:-DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;TableEndpoint=http://host.docker.internal:10002/devstoreaccount1;}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT:-devstoreaccount1}

  coreai-mcu-prompts-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "${CORE_AI_PROMPTS_TABLE_PORT:-10002}:10002"
    volumes:
      - azurite_data:/data

volumes:
  azurite_data:
